### ISSUE TITLE
import timesearch_modules error

### ISSUE THREAD

**Issue by adikami5665** [voussoir/timesearch#14]
D:\software\timesearch-master>python timesearch.py get_submissions -r gifs
Traceback (most recent call last):
  File "D:\software\timesearch-master\timesearch.py", line 16, in <module>
    import timesearch_modules
  File "D:\software\timesearch-master\timesearch_modules\__init__.py", line 282, in <module>
    DOCSTRING = betterhelp.add_previews(DOCSTRING, MODULE_DOCSTRINGS)
AttributeError: module 'voussoirkit.betterhelp' has no attribute 'add_previews'

This is what I get after installing python 3.10 form 3.8 version

**Comment by voussoir** [comment]
Hi, could you do a `git pull` on the timesearch repository? You could also `pip install voussoirkit --upgrade` to make sure that is most up to date as well. It looks like your timesearch files are a little older and I have since made changes to the voussoirkit library.

Let me know what happens. Thanks!

**Comment by adikami5665** [comment]
After redownloading the files every thing works fine 
thanks

**Comment by voussoir** [comment]
Glad to hear it, let me know if anything else comes up.
