### ISSUE TITLE
dont work no more any way around with local dumps??

### ISSUE THREAD

**Issue by adikami5665** [voussoir/timesearch#20]
So i got the local dumps downloaded but I don't know how to proceed and get subreddit file like I used to get in db format. any help to move forward. I know the api is down but can https://github.com/yakabuff/redarc help in any way to generate files like before.

**Comment by DoaJCBlogger** [comment]
Do you mean that you downloaded the Zstandard files?

**Comment by adikami5665** [comment]
yes

**Comment by voussoir** [comment]
Hi guys. I have added a new module to timesearch that can import the archive files into a timesearch database.

zst is a compressed format. Please use a tool like [7-Zip](https://www.7-zip.org/) to extract the actual json files. The files inside the archive do not have a file extension, but that's ok.

Please do a `python -m pip install voussoirkit --upgrade` just in case I've changed anything in my libraries since you last updated.

Please do a `git pull` of your timesearch repository to get the new commit 8b3fe524.

Then,

`python timesearch ingest_jsonfile robotwars_submissions -r robotwars`

`python timesearch ingest_jsonfile robotwars_comments -r robotwars`

Hope that helps

![image](https://github.com/voussoir/timesearch/assets/7299570/9053eedd-ee3a-40a9-abca-5bc9475251c6)

![image](https://github.com/voussoir/timesearch/assets/7299570/55bdc3a3-bc0b-4bd6-85b4-0c6b6e9e4b24)

**Comment by DoaJCBlogger** [comment]
This is great. Thank you. The only thing I would suggest is adding support for Zstandard so you don't have to decompress them.
